version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: [1]
      POSTGRES_DB: uni-stay-dn-db
    ports:
      - "3004:5432"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
