services:
  app:
    build: .
    container_name: be-app
    ports:
      - "6969:6969"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://postgres:1@db:5432/uni-stay-dn-db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: uni-stay-dn-db
    ports:
      - "3005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 10s
      retries: 5
  redis:
    image: redis
    container_name: my-redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./src/core/config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
volumes:
  postgres_data:
  redis_data:
