# Security: Require password to access
requirepass MatKhauCuaBan123

# Persistence: Enable AOF
appendonly yes
appendfsync everysec

# Memory limit (Avoid crashing VPS/Computer)
maxmemory 256mb
maxmemory-policy allkeys-lru