name: Deploy Backend Local Server

on:
  push:
    branches: ["develop", "main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["develop", "main"]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: integrating new code (backend)
        run: |
          cd /var/www/unistay/backend

          git pull origin develop

          docker compose --profile tools run --rm migrate

          docker compose up -d --build app
