name: Deploy Backend Local Server

on:
  push:
    branches: ["develop", "main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["develop", "main"]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: integrating new code (backend)
        run: |
          cd /var/www/unistay/backend

          git pull origin develop

          sudo docker compose --profile tools run --rm migrate

          sudo docker compose up -d --build app
