name: Deploy Frontend Local Server

on:
  push:
    branches: ["develop", "main"]
    paths:
      - "frontend/**"
  pull_request:
    branches: ["develop", "main"]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: integrating new code (frontend)
        run: |
          cd /var/www/unistay/frontend

          git pull origin develop

          npm ci
            
          npm run build
